CREATE TABLE IF NOT EXISTS promotion_grants (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL,
  bonus_cents BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
