name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - name: Run tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "false"
          TESTCONTAINERS_CHECKS_DISABLE: "true"
        run: |
          ./gradlew --no-daemon test
      - name: Publish test reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test
